name = "Phunny"
uuid = "3b98769a-403b-40a5-9695-f803a8ef7baa"
version = "0.0.9-DEV"
authors = ["Isaac Ownby", "Immanuel Schmidt"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Sunny = "2b4a2ac8-8f8b-43e8-abf4-3cb0c45e8736"

[compat]
StaticArrays = "1"
Sunny = "0.7, 1.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
